### ISSUE TITLE
Weird beheivor while importing m3 HOTS models.

### ISSUE THREAD

**Issue by Rayveens** [Solstice245/m3studio#1]
Hello everyone, i been trying to port some of the hots model into blender, but im hving some issues while porting some heroes, like Ragnaros as example, the animations are 90% broken, and this also happens with the vertexs, 
![image](https://github.com/Solstice245/m3studio/assets/103624048/25bb5d86-1ffb-4e16-a362-82496e2c60d5)

im doing something wrong? or its just a glich in the m3 model?

**Comment by Solstice245** [comment]
Can you attach the m3 file so that I can take a look? I don't have HotS installed, so it'd be a bit troublesome to grab it myself.

**Comment by Rayveens** [comment]
surething. sorry had to zip it.

**Comment by Solstice245** [comment]
Is there a specific animation for which this issue occurs? And you made sure you're using the latest version of the software? I imported those particular files and looked things over, but didn't see anything which looked incorrect.

**Comment by Rayveens** [comment]
i got the recently update i think, i just downloaded it yesterday from this repo, there is a way in blender to check if its the last one? here a video of my process of export, i managed to fix the weird behavior of the face clicking in the box "Bone Envelopes".

but still having lots of animation broken, i dont know if it just the model broken or if is something related to my import way.

https://drive.google.com/file/d/1aCNMnjAr-DfKrmjA8l6-VS6MXuJHwkUE/view?usp=sharing

**Comment by Solstice245** [comment]
Most of the animations have multiple tracks. What you're seeing for most is the "Jaw" animation track, which does not include the full animation. Please look at the "full" animation track and tell me what you see. Also, when importing m3a, you probably should be using the import operation from the armature itself. (Select armature object > Object Properties > M3 Import/Export Panel > Import M3 operation)

**Comment by Rayveens** [comment]
YOU ARE THE BEST. This thread its pure Gold. both issues fixed when imported the armature from the M3 Import. THANK YOU.

**Comment by Solstice245** [comment]
Seeing as you are content that the problem has been addressed, I will go ahead and close this issue. If for some reason you find yourself coming back to this though, you can request for it to be reopened.
