### ISSUE TITLE
Weird interaccion when some HoS Animation being improted

### ISSUE THREAD

**Issue by Rayveens** [Solstice245/m3studio#2]
i just wanted to show it, maybe its intended of this way, or maybe its some sort of bug but, some models, some of the animations are split in a half, even when they say "full", here is an example, its suppose to be the full animation of walk but instead its splitted in 2 separated parts, is this the intended behevior?

https://github.com/Solstice245/m3studio/assets/103624048/422aa62c-1b8e-4c36-959b-d9c3c4c0facc

thanks for your  time, and this wonderfull addon.

**Comment by Solstice245** [comment]
"full" is just the generic name for the base layer of animation. It does not necessarily contain all the animation data. In general, anything in "full" is never intended to be played concurrently with other "full" animation tracks in other animation groups.

In short, this is the intended function, though I have considered perhaps changing the animation data architecture. Either such that is is like m3addon, where tracks are split on the basis of storing a string containing fcurve identifiers instead of separate actions, or combining the data from all animation groups into one action, and the data being separated on the timeline, such as how it is presented in 3dsmax m3 workflows.

**Comment by Rayveens** [comment]
i see, so if i want to mix boths parts of the animation, what should i do? get the 3dstudio max?

**Comment by Solstice245** [comment]
So you are trying to combine the combine the data of multiple actions? I assume for a purpose outside of using them in SC2?

**Comment by Rayveens** [comment]
my goal its just exporthem as a giff, with that in mind, i just want a full woking walk animation

**Comment by Solstice245** [comment]
I see. Well, you'll just need to combine them manually (or with some other utility script for that purpose, if it exists) or use a different importer which imports it in a format that is already the way you want it.

**Comment by Rayveens** [comment]
thx man, iwill see how can i fix  this, im closing this, there is no point on leaving it open.

**Comment by BlackBoar101** [comment]
@Rayveens excuse me can you tell me how to attach textures to the model?
i can view models already in blender.

<img width="664" height="130" alt="Image" src="https://github.com/user-attachments/assets/c2d97e0b-d947-4bef-b282-e2a32a1263f0" />

**Comment by Solstice245** [comment]
> @Rayveens excuse me can you tell me how to attach textures to the model?
> i can view models already in blender.
> 
> <img width="664" height="130" alt="Image" src="https://github.com/user-attachments/assets/c2d97e0b-d947-4bef-b282-e2a32a1263f0" />

This is not a feature of m3studio. Rather, it is accomplished using native Blender shader nodes via Blender materials.

Since this is a general Blender topic, there are ample online learning resources available. I recommend you go search for some.

**Comment by Rayveens** [comment]
> @Rayveens excuse me can you tell me how to attach textures to the model?
> i can view models already in blender.
> 
> <img width="664" height="130" alt="Image" src="https://github.com/user-attachments/assets/c2d97e0b-d947-4bef-b282-e2a32a1263f0" />

Yea You just create a material and assign it on the model

**Comment by BlackBoar101** [comment]
@Solstice245 @Rayveens thanks i can see full model with skins already.
just need to throw textures in the same folder with .M3 model and click **shading** in blender.
